version: '3'

services:
  app:
    image: clojure:lein-2.7.1-alpine
    working_dir: "${PWD}"
    command: lein repl :headless :host "0.0.0.0" :port 4100
    ports:
      - "4100:4100" # repl
      - "4101:4101" # http
    volumes:
      - ".:${PWD}"
      - ~/.lein:/root/.lein:ro
